import Providers from "@/utils/provider";
import React from "react";
import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { Analytics } from "@/components/analytics";
import { ModeToggle } from "@/components/mode-toggle";
import { Toaster } from "react-hot-toast";
import { Suspense } from "react";
import AuthStatus from "@/components/auth-status";

import Header from "../components/Header";
import Footer from "../components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Person Bitacora",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-50 ${inter.className}`}
      >
        <>
          <Providers>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              <Toaster />
              <Suspense fallback="Loading...">
                {/* @ts-expect-error Async Server Component */}
                <AuthStatus />
              </Suspense>
              <Header />

              <main className="py-1">{children}</main>
              <Analytics />
            </ThemeProvider>
          </Providers>
        </>
      </body>
    </html>
  );
}
